setTimeout(function () {$("#spacejam").prepend('<p>Everybody get up its time to slam now</p>');}, 1000);
setTimeout(function () {$("#spacejam").prepend('<p>We got a real jam goin down</p>');}, 4300);
setTimeout(function () {$("#spacejam").prepend('<p>Welcome to the Space Jam</p>');}, 7000);
setTimeout(function () {$("#spacejam").prepend('<p>Heres your chance, do your dance at the Space Jam</p>');}, 9300);
setTimeout(function () {$("#spacejam").prepend('<p>Alright</p>');}, 13000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on and slam, and welcome to the jam</p>');}, 22500);
setTimeout(function () {$("#spacejam").prepend('<p>Come on and slam, if you wanna jam</p>');}, 26000);
setTimeout(function () {$("#spacejam").prepend('<p>Hey you, watcha gon do</p>');}, 37000);
setTimeout(function () {$("#spacejam").prepend('<p>Hey you, watcha gon do</p>');}, 38700);
setTimeout(function () {$("#spacejam").prepend('<p>Hey you, watcha gon do</p>');}, 40400);
setTimeout(function () {$("#spacejam").prepend('<p>Hey you, watcha gon do</p>');}, 42200);
setTimeout(function () {$("#spacejam").prepend('<p>Party people in the house lets go</p>');}, 44000);
setTimeout(function () {$("#spacejam").prepend('<p>Its your boy "Jayski" aight so</p>');}, 45800);
setTimeout(function () {$("#spacejam").prepend('<p>Pass that thing and watch me flex</p>');}, 47800);
setTimeout(function () {$("#spacejam").prepend('<p>Behind my back, you know whats next</p>');}, 49500);
setTimeout(function () {$("#spacejam").prepend('<p>To the jam, all in your face</p>');}, 51400);
setTimeout(function () {$("#spacejam").prepend('<p>Wassup, just feel the bass</p>');}, 53150);
setTimeout(function () {$("#spacejam").prepend('<p>Drop it, rock it, down the room</p>');}, 55000);
setTimeout(function () {$("#spacejam").prepend('<p>Shake it, quake it, space kaboom</p>');}, 57000);
setTimeout(function () {$("#spacejam").prepend('<p>Just work that body, work that body</p>');}, 58600);
setTimeout(function () {$("#spacejam").prepend('<p>Make sure you dont hurt nobody</p>');}, 60500);
setTimeout(function () {$("#spacejam").prepend('<p>Get wild and lose your mind</p>');}, 62600);
setTimeout(function () {$("#spacejam").prepend('<p>Take this thing into overtime</p>');}, 64000);
setTimeout(function () {$("#spacejam").prepend('<p>Hey DJ, turn it up</p>');}, 66000);
setTimeout(function () {$("#spacejam").prepend('<p>QCD gon burn it up</p>');}, 68000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on yall get on the floor</p>');}, 69800);
setTimeout(function () {$("#spacejam").prepend('<p>So hey, lets go aight</p>');}, 71000);
setTimeout(function () {$("#spacejam").prepend('<p>Everybody get up its time to slam now</p>');}, 73500);
setTimeout(function () {$("#spacejam").prepend('<p>We got a real jam goin down</p>');}, 76700);
setTimeout(function () {$("#spacejam").prepend('<p>Welcome to the Space Jam</p>');}, 79500);
setTimeout(function () {$("#spacejam").prepend('<p>Heres your chance, do your dance at the Space Jam</p>');}, 82000);
setTimeout(function () {$("#spacejam").prepend('<p>Alright</p>');}, 85500);
setTimeout(function () {$("#spacejam").prepend('<p>Wave your hands in the air if you feel fine</p>');}, 87000);
setTimeout(function () {$("#spacejam").prepend('<p>Were gonna take it into overtime</p>');}, 89000);
setTimeout(function () {$("#spacejam").prepend('<p>Welcome to the Space Jam</p>');}, 90000);
setTimeout(function () {$("#spacejam").prepend('<p>Heres your chance, do your dance at the Space Jam</p>');}, 92000);
setTimeout(function () {$("#spacejam").prepend('<p>Alright</p>');}, 111000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on, its time to get hyped say "hoop, there it is"</p>');}, 114000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on, all the fellas say "hoop, there it is"</p>');}, 117000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on, one time for the ladies, say "hoop, there it is"</p>');}, 120000);
setTimeout(function () {$("#spacejam").prepend('<p>Now, all the fellas, say "hoop, there it is"</p>');}, 123000);
setTimeout(function () {$("#spacejam").prepend('<p>Right</p>');}, 126000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on and run, baby run</p>');}, 129000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on, come on, do it, run baby run</p>');}, 132000);
setTimeout(function () {$("#spacejam").prepend('<p>Yeah, you wanna hoop, so shoot, baby shoot</p>');}, 135000);
setTimeout(function () {$("#spacejam").prepend('<p>Uh, its time to hoop, so shoot, baby, shoot, baby</p>');}, 138000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on and slam, and welcome to the jam</p>');}, 141000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on and slam, if you wanna jam</p>');}, 144000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on and slam, and welcome to the jam</p>');}, 147000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on and slam, if you wanna jam</p>');}, 150000);
setTimeout(function () {$("#spacejam").prepend('<p>Slam, bam, thank you maam</p>');}, 153000);
setTimeout(function () {$("#spacejam").prepend('<p>Get on the floor and jam</p>');}, 156000);
setTimeout(function () {$("#spacejam").prepend('<p>Its the QCD on the microphone</p>');}, 159000);
setTimeout(function () {$("#spacejam").prepend('<p>Girl you got me in the zone</p>');}, 162000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on, come on and start the game</p>');}, 165000);
setTimeout(function () {$("#spacejam").prepend('<p>Break it down, tell me your name</p>');}, 168000);
setTimeout(function () {$("#spacejam").prepend('<p>We the team, Im the coach</p>');}, 171000);
setTimeout(function () {$("#spacejam").prepend('<p>Lets dance all night from coast to coast</p>');}, 174000);
setTimeout(function () {$("#spacejam").prepend('<p>Just slide, from left to right</p>');}, 177000);
setTimeout(function () {$("#spacejam").prepend('<p>Just slide, yourself tonight</p>');}, 180000);
setTimeout(function () {$("#spacejam").prepend('<p>QCD, drop the bass</p>');}, 183000);
setTimeout(function () {$("#spacejam").prepend('<p>3-1-1 all in your face</p>');}, 186000);
setTimeout(function () {$("#spacejam").prepend('<p>Jam on it, lets have some fun</p>');}, 189000);
setTimeout(function () {$("#spacejam").prepend('<p>Jam on it, one on one</p>');}, 192000);
setTimeout(function () {$("#spacejam").prepend('<p>You run the "O" and I run the "D"</p>');}, 195000);
setTimeout(function () {$("#spacejam").prepend('<p>So come on baby, just jam for me</p>');}, 198000);
setTimeout(function () {$("#spacejam").prepend('<p>Everybody get up its time to slam now</p>');}, 201000);
setTimeout(function () {$("#spacejam").prepend('<p>We got a real jam goin down</p>');}, 204000);
setTimeout(function () {$("#spacejam").prepend('<p>Welcome to the Space Jam</p>');}, 207000);
setTimeout(function () {$("#spacejam").prepend('<p>Heres your chance, do your dance at the Space Jam</p>');}, 210000);
setTimeout(function () {$("#spacejam").prepend('<p>Alright</p>');}, 213000);
setTimeout(function () {$("#spacejam").prepend('<p>Wave your hands in the air if you feel fine</p>');}, 216000);
setTimeout(function () {$("#spacejam").prepend('<p>Were gonna take it into overtime</p>');}, 219000);
setTimeout(function () {$("#spacejam").prepend('<p>Welcome to the Space Jam</p>');}, 222000);
setTimeout(function () {$("#spacejam").prepend('<p>Heres your chance, do your dance at the Space Jam</p>');}, 225000);
setTimeout(function () {$("#spacejam").prepend('<p>Alright</p>');}, 228000);
setTimeout(function () {$("#spacejam").prepend('<p>Hey ladies</p>');}, 231000);
setTimeout(function () {$("#spacejam").prepend('<p>(Yeah)</p>');}, 232000);
setTimeout(function () {$("#spacejam").prepend('<p>Yall ready to stop?</p>');}, 236000);
setTimeout(function () {$("#spacejam").prepend('<p>(No)</p>');}, 240000);
setTimeout(function () {$("#spacejam").prepend('<p>And yall wanna know why?</p>');}, 243000);
setTimeout(function () {$("#spacejam").prepend('<p>(Why?)</p>');}, 246000);
setTimeout(function () {$("#spacejam").prepend('<p>Cause its the Slam Jam</p>');}, 249000);
setTimeout(function () {$("#spacejam").prepend('<p>Fellas</p>');}, 252000);
setTimeout(function () {$("#spacejam").prepend('<p>(Yeah)</p>');}, 255000);
setTimeout(function () {$("#spacejam").prepend('<p>Yall ready to stop?</p>');}, 258000);
setTimeout(function () {$("#spacejam").prepend('<p>(No)</p>');}, 261000);
setTimeout(function () {$("#spacejam").prepend('<p>Yall wanna know why?</p>');}, 264000);
setTimeout(function () {$("#spacejam").prepend('<p>(Why?)</p>');}, 267000);
setTimeout(function () {$("#spacejam").prepend('<p>Its time to Slam Jam</p>');}, 270000);
setTimeout(function () {$("#spacejam").prepend('<p>Everybody get up its time to slam now</p>');}, 273000);
setTimeout(function () {$("#spacejam").prepend('<p>We got a real jam goin down</p>');}, 276000);
setTimeout(function () {$("#spacejam").prepend('<p>Welcome to the Space Jam</p>');}, 279000);
setTimeout(function () {$("#spacejam").prepend('<p>Heres your chance, do your dance at the Space Jam</p>');}, 282000);
setTimeout(function () {$("#spacejam").prepend('<p>Alright</p>');}, 285000);
setTimeout(function () {$("#spacejam").prepend('<p>Wave your hands in the air if you feel fine</p>');}, 288000);
setTimeout(function () {$("#spacejam").prepend('<p>Were gonna take it into overtime</p>');}, 291000);
setTimeout(function () {$("#spacejam").prepend('<p>Welcome to the Space Jam</p>');}, 294000);
setTimeout(function () {$("#spacejam").prepend('<p>Heres your chance, do your dance at the Space Jam</p>');}, 297000);
setTimeout(function () {$("#spacejam").prepend('<p>Alright</p>');}, 300000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on, everybody say "na na na na na"</p>');}, 303000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on, come on, let me hear you say "hey-ey-ey-yo"</p>');}, 306000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on, come on, everybody, "na na na na na"</p>');}, 309000);
setTimeout(function () {$("#spacejam").prepend('<p>Just take the time and lets say "hey-ey-ey-yo"</p>');}, 312000);
setTimeout(function () {$("#spacejam").prepend('<p>Check it out, it it out, yall ready for this</p>');}, 315000);
setTimeout(function () {$("#spacejam").prepend('<p>(You know it)</p>');}, 318000);
setTimeout(function () {$("#spacejam").prepend('<p>Nah, yall aint ready, yall ready for this</p>');}, 321000);
setTimeout(function () {$("#spacejam").prepend('<p>(You know it)</p>');}, 324000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on, check it out, yall ready to jam</p>');}, 327000);
setTimeout(function () {$("#spacejam").prepend('<p>(You know it)</p>');}, 330000);
setTimeout(function () {$("#spacejam").prepend('<p>I, I, I dont think so, yall ready to jam</p>');}, 333000);
setTimeout(function () {$("#spacejam").prepend('<p>(You know it)</p>');}, 336000);
setTimeout(function () {$("#spacejam").prepend('<p>Come on</p>');}, 339000);
